def set_role_prompt(prompt_parameters):
    question_prompt = \
        f"""
        Generate {prompt_parameters.get("no_of_questions", 5)} Math Multiple Choice Questions, 
        where there are 4 choices out of which, only one is the right answer. 
        
        Along with the choice, you must also expect and accept an explanation as to why I made this choice

        Format of the question and the answer is:
        ```
        Question text
        A. Choice 1
        B. Choice 2
        C. Choice 3
        D. Choice 4
        ```
        
        {retrieve_topics_prompt(prompt_parameters.get("topics", ["Linear algebra", "Calculus", "Probability", "Discrete Mathematics"]))} 

        Generate the next question once I have given the answer and the explanation for the choice for the question 
        generated by you. 
        Choice can either be `A`, `B`, `C`, or `D`. 
        Do not proceed forward if any other option has been given to you apart from the 4 mentioned options
        
        You will also give a score for the explanation in the range from 0 to 10, 
        however, this will not be counted toward the total score, 
        it is a reference for me on how well I have explained why I hose this option.

        Once I have given the responses to all the questions, you will calculate the score based on the choices. 
        I have made and give me a report on what I need to do to improve."""

    return question_prompt


def retrieve_topics_prompt(topics):
    topics_prompt = f"""
        Topics to choose from are:
        """

    for each in topics:
        topics_prompt += f"\n- {each}"

    return topics_prompt


def generate_study_plan_prompt():
    return """
    Can you give me a study plan for improvement based on the said topics? Given that I am free for these hours for each day of the week as shown below:
    
    Monday: 5:30 PM - 8:00 PM, 10:00 PM - 11:00 PM
    Tuesday: 5:30 PM - 8:00 PM, 10:00 PM - 11:00 PM
    Wednesday: 5:30 PM - 8:00 PM, 10:00 PM - 11:00 PM
    Thursday: 5:30 PM - 8:00 PM, 10:00 PM - 11:00 PM
    Friday: 5:30 PM - 8:00 PM, 10:00 PM - 11:00 PM
    Saturday: 1:00 PM - 5:00 PM, 7:30 PM - 9:00 PM
    Sunday: 10:00 AM - 2:00 PM, 3:00 PM - 6:00 PM, 7:30 PM - 9:00 PM
    """


def generate_improvement_prompt():
    return """
    Please give me a detailed report on what I need to improve upon. Please give it to me in the following format. 
    
    ```Topic: Scope for improvement```
    
    The topic is the one based on which the questions were asked. Please do not include any websites for reference. Just add in books to read
    
    The scope for improvement will be based on the explanation I had given for my choice for all the questions
    """


def get_intro_prompt(intro_parameters):
    return f"""Hello, my name is {intro_parameters["name"]} and I belong to the grade {intro_parameters["grade"]}. I am being taught by {intro_parameters["teacher"]}"""